/**
 * Loose TypeScript types describing Svelte 5 *private* internal shapes
 * we read from the page context. These are intentionally permissive
 * (optional everywhere, `unknown` for values) because Svelte may change
 * field names or types across minor versions. The `compat` layer is the
 * one place allowed to access these fields directly.
 */

export interface Value {
  v: unknown;
  reactions?: Reaction[] | null;
  rv?: number;
  wv?: number;
  label?: string | null;
}

export interface Reaction {
  v?: unknown;
  fn?: ((...args: unknown[]) => unknown) | null;
  deps?: unknown[] | null;
  reactions?: Reaction[] | null;
  rv?: number;
  wv?: number;
  label?: string | null;
  teardown?: unknown;
  ctx?: ReactionCtx | null;
}

export interface ReactionCtx {
  uid?: unknown;
  function?: ComponentFn | null;
}

export type ComponentFn = ((...args: unknown[]) => unknown) & {
  name?: string;
  [filenameSymbol: symbol]: string | undefined;
};

declare global {
  interface Window {
    __svelte_devtools__?: SvelteDevtoolsBridge;
    __svelte?: { v?: string };
  }
  interface Element {
    __svelte_meta?: { file?: string; line?: number; column?: number };
  }
}

/**
 * The minimum surface other modules (transform.ts callers) expect to find
 * on `window.__svelte_devtools__`. Keep this in sync with the call sites
 * generated by the AST transform.
 */
export interface SvelteDevtoolsBridge {
  onPush: (name: string, props: unknown, componentFn: ComponentFn) => string;
  onPop: () => string | undefined;
  registerSignal: (
    signal: Value,
    label: string | null,
    componentId?: string | null,
    signalType?: 'state' | 'derived' | 'props',
  ) => void;
  registerEffect: (fn: (...args: unknown[]) => unknown, componentId?: string | null) => string;
  preMutation: (signal: Value) => void;
  onMutation: (signal: Value) => void;
  wrapEffect: (fn: (...args: unknown[]) => unknown, effectId: string) => (...args: unknown[]) => unknown;
}
